### ISSUE TITLE
Im new and i don't know how to use this

### ISSUE THREAD

**Issue by ghost** [AndrewWang996/MangaTranslator#1]
Im new and i don't know how to use this

**Comment by AndrewWang996** [comment]
Hi Cartals. Thanks for reaching out! This is a side project I worked on in my free time during school during last year, and I never got around to making it easily usable for others. I have a lot less time due to ongoing projects, but you can check out other better maintained repos for automatic manga translation (https://www.quora.com/Is-there-a-software-that-can-translate-mangas.) I might be willing to jump back into this in a couple months if you are okay with waiting.

**Comment by ghost** [comment]
i will waiting for you

**Comment by ghost** [comment]
> Hi Cartals. Thanks for reaching out! This is a side project I worked on in my free time during school during last year, and I never got around to making it easily usable for others. I have a lot less time due to ongoing projects, but you can check out other better maintained repos for automatic manga translation (https://www.quora.com/Is-there-a-software-that-can-translate-mangas.) I might be willing to jump back into this in a couple months if you are okay with waiting.

can you explain how can i use this im very impatient and i wanna read mangas

**Comment by AndrewWang996** [comment]
Hi Cartals. Sorry I'm not able to help much right now. The translations provided by my code are pretty limited, because they depend on a pipeline of Google OCR and Translate, which won't necessarily capture a lot of the subtleties of the original text. If you want, you can go on sites such as mangadex for English translations that update fairly quickly for any remotely popular series.

**Comment by cartals** [comment]
what i want that manga doesnt translate

**Comment by ghost** [comment]
it been 1 year i still wait you :)
